name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run sync action
        uses: ./  
        with:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          upstream_repo: ${{ secrets.UPSTREAM_REPO }}
          branch_name: "main"
          git_user_email: ${{ secrets.GIT_USER_EMAIL }}
          git_user_name: ${{ secrets.GIT_USER_NAME }}
