name: Upstream Sync

on:
  workflow_dispatch: # Manual trigger ke liye

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Pull upstream changes
        uses: wei/pull@v1
        with:
          upstream: j-hc/revanced-magisk-module
          token: ${{ secrets.GITHUB_TOKEN }}
