name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  UPSTREAM_REPO: j-hc/revanced-magisk-module
  UPSTREAM_BRANCH: main
  FORK_BRANCH: main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync with Upstream
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          branch: ${{ env.UPSTREAM_BRANCH }}
          target_branch: ${{ env.FORK_BRANCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
