name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync upstream repository
        uses: DevMatrixs/upstream-sync-action@v1.0.0
        with:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          UPSTREAM_REPO: https://github.com/j-hc/revanced-magisk-module.git
          SYNC_BRANCH: 'main'
