name: Sync Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync upstream
        uses: DevMatrixs/upstream-sync-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repo: 'j-hc/revanced-magisk-module'
          source_branch: 'main'
          target_branch: 'main'
