name: Sync with Upstream

# Trigger workflow manually
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync fork with upstream
        uses: DevMatrixs/upstream-sync-action@v1.0.0 # Path to your custom action
        env:
          UPSTREAM_REPO: https://github.com/j-hc/revanced-magisk-module.git
          BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GIT_USER_NAME: DevMatrixs
          GIT_USER_EMAIL: custom@example.com
