name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync with upstream
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: ${{ secrets.UPSTREAM_REPO }}
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          source_repo: ${{ secrets.UPSTREAM_REPO }}
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
