name: Upstream Sync

on:
  workflow_dispatch: # Manual trigger के लिए

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full clone

      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: j-hc/revanced-magisk-module
          upstream_sync_branch: main
