name: Sync Fork with Upstream

on:
  workflow_dispatch:  # Only allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync with upstream
        uses: DevMatrixs/upstream-sync-action@v1.0.0
        with:
          upstream-repo: 'j-hc/revanced-magisk-module'
          branch: 'main'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          log-level: 'debug'
