name: Sync Upstream Code

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch full history to ensure proper sync

      # Step 2: Sync with Upstream using repo-sync/repo-sync
      - name: Sync with Upstream
        uses: repo-sync/repo-sync@v2.6
        with:
          source_repo: https://github.com/j-hc/revanced-magisk-module  # Upstream repo URL
          source_branch: main                                         # Upstream branch
          destination_branch: main                                    # Branch in your fork
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
          debug: true                                                 # Show detailed logs
