name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout downstream repository
        uses: actions/checkout@v3

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
