name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      # Defining environment variables that will be used across all steps
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      UPSTREAM_REPO: ${{ secrets.UPSTREAM_REPO }}
      BRANCH_NAME: "main"
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run sync action
        uses: DevMatrixs/upstream-sync-action@v1.0.0
        with:
          WORKFLOW_TOKEN: ${{ env.WORKFLOW_TOKEN }}
          upstream_repo: ${{ env.UPSTREAM_REPO }}
          branch_name: ${{ env.BRANCH_NAME }}
          git_user_email: ${{ env.GIT_USER_EMAIL }}
          git_user_name: ${{ env.GIT_USER_NAME }}
