name: Sync Upstream to Downstream

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Run Sync Upstream Action
      uses: DevMatrixss/upstream-sync@v1.1.0
      with:
        upstream_repo: "j-hc/revanced-magisk-module"
        upstream_branch: "main"
        downstream_branch: "main"
        custom_token: "${{ secrets.CUSTOM_TOKEN }}"
