name: Sync with Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with upstream repository
        uses: DevMatrixs/upstream-sync-action@v1.0.0
        with:
          GIT_NAME: 'GitHub Actions'
          GIT_EMAIL: 'actions@github.com'
          UPSTREAM_REPO: 'j-hc/revanced-magisk-module'
          TARGET_BRANCH: 'main'
          UPSTREAM_BRANCH: 'main'
          FORCE_PUSH: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
