name: Sync with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repository
        uses: tibdex/github-repo-sync@v2
        with:
          source_repo: j-hc/revanced-magisk-module
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
