name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  UPSTREAM_REPO: j-hc/revanced-magisk-module
  UPSTREAM_BRANCH: main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      - name: Add Upstream and Sync
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}
          git fetch upstream ${{ env.UPSTREAM_BRANCH }}
          git merge upstream/${{ env.UPSTREAM_BRANCH }} --no-edit
          git push origin ${{ env.UPSTREAM_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
