name: Upstream Sync

on:
  workflow_dispatch: # Manual trigger के लिए

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: 'j-hc/revanced-magisk-module'
      TARGET_BRANCH: 'main'
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full clone

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Fetch upstream repository
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout ${{ env.TARGET_BRANCH }}
          git merge upstream/${{ env.TARGET_BRANCH }}

      - name: Push changes to target branch
        run: |
          git push origin ${{ env.TARGET_BRANCH }}
