name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # Har din raat 12 baje chalega
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with Upstream
        uses: wei/git-sync@v2
        with:
          source_repo: j-hc/revanced-magisk-module          # Upstream repository ka naam
          source_branch: main                               # Upstream branch
          destination_repo: ${{ github.repository }}        # Aapki forked repository
          destination_branch: main                          # Aapki fork repository ki branch (e.g., main)
