name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  UPSTREAM_REPO: j-hc/revanced-magisk-module
  BRANCH: main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: repo-sync/pull-request@v2
        with:
          source_repo: ${{ env.UPSTREAM_REPO }}
          source_branch: ${{ env.BRANCH }}
          destination_branch: ${{ env.BRANCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
