name: Sync Fork

on:
  workflow_dispatch: # Manual trigger ke liye

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3

      - name: Sync with upstream
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          upstream_repository: j-hc/revanced-magisk-module
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
