name: Upstream Sync

on:
  workflow_dispatch: # Manual trigger ke liye

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Upstream
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          source_repo: "j-hc/revanced-magisk-module"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
