name: Upstream Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream

      - name: Sync with upstream
        uses: XueMoMo/Sync-Fork-action@v1.0.6
        with:
          upstream_repository: j-hc/revanced-magisk-module
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
